[versions]
kotlin = "1.7.21"
kover = "0.6.1"
okio = "3.2.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.22.0-RC3" }
test-aggregation = { id = "test-report-aggregation", version = "1.0.0" }
shadowJar = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }


[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version = "1.22.0-RC3" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
